### PR TITLE
Merge remote-tracking branch 'origin/master'

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4303/)

**Comment by prakashsurya** [comment]
I had to do relatively simple (i.e. adopt the fix from our master branch) manual merge conflict resolution due to #21 #22 and #23

**Comment by pzakha** [comment]
Is there any differences with `origin/master` at that point?

FYI if you want to merge with a branch and ignore any differences, you can run:
```
git merge -X theirs origin/master
```
Running this brings 6.0/stage to the same changes as master without any conflicts.

**Comment by prakashsurya** [comment]
Yea, I know about `-X`, but I try not to use it unless I'm certain that it's the right option to use (e.g. have some sort of idea about how it'll resolve the differences, and know that's likely to do the right thing).

Since I now have a better idea that `-X` will likely do what we want, I'll open another PR using that approach (since I do think it's better to use it than not, when appropriate).

**Comment by prakashsurya** [comment]
Closing in favor of #28

**Pull request closed without merging**
