### PR TITLE
Fix merge conflict in cloud-init

### PR DESCRIPTION
**Pull request by pcd1193182**
This PR fixes the upstream merge conflict with cloud-init seen in http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/userland/job/update/485/console . The merge conflict was in `tools/read-version`

### CODE REVIEW

**Comment by pzakha** [comment]
Could you post the changes you've made specifically, as the PR shows all the 300 files modified by upstream?
Also, could you add a link to ab-pre-push?

**Comment by prakashsurya** [comment]
@pzakha that can be obtained like so:
```
± g f origin pull/19/head &&  g show FETCH_HEAD
commit 9d84490dc806673ff85e7bcb7da6cea2723b5b2b
Merge: c5b5ab9e 1a838faf
Author: Paul Dagnelie <pcd@delphix.com>
Date:   Tue Jul 21 11:59:06 2020 -0700

    Merge branch 'refs/heads/upstream-HEAD' into repo-HEAD

diff --cc tools/read-version
index 4bea4a29,02c90643..563a23bc
--- a/tools/read-version
+++ b/tools/read-version
@@@ -65,12 -65,13 +65,19 @@@ output_json = '--json' in sys.arg
  src_version = ci_version.version_string()
  version_long = None
  
+ # If we're performing CI for a new release branch (which our tooling creates
+ # with an "upstream/" prefix), then we don't want to enforce strict version
+ # matching because we know it will fail.
+ is_release_branch_ci = (
+     os.environ.get("TRAVIS_PULL_REQUEST_BRANCH", "").startswith("upstream/")
+ )
 -if is_gitdir(_tdir) and which("git") and not is_release_branch_ci:
++
 +# Delphix: we set our own version
 +# pylint: disable=w0125
 +if True:
 +    version = src_version
 +    version_long = None
- elif is_gitdir(_tdir) and which("git"):
++elif is_gitdir(_tdir) and which("git") and not is_release_branch_ci:
      flags = []
      if use_tags:
          flags = ['--tags']
```

**Comment by pzakha** [comment]
Ah thanks @prakashsurya, that's a neat trick

**Comment by pcd1193182** [comment]
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3778/console In progress

**Comment by pcd1193182** [comment]
I updated the PR by removing the .github directory; the checks imposed by the upstream repository don't apply to us, since we don't need to have signed the canonical CLA, and we don't need the stale PR closing workflow.

**Pull request merged**
