### PR TITLE
NoCloud: allow using system-uuid as instance id

### PR DESCRIPTION
**Pull request by pzakha**
## Description
Allow using a dynamic instance-id based on the system's uuid for NoCloud VMs when special value `iid-system-uuid` is passed as the instance ID in the seed meta-data. As the name suggests it, NoCloud VMs are those that do not run in a public cloud, such as our ESX deployments. Using a dynamic instance-id instead of a fixed one for NoCloud deployments allows cloud-init to detect instance changes when we clone existing VMs or groups in dcenter and to execute its new instance logic such as network configuration.

## Why we need this change
This change is a pre-requisite for https://jira.delphix.com/browse/DLPX-64347. In particular, it is required for properly enabling cloud-init on ESX. 

If we have cloud-init disabled, then the network interfaces are never configured and our VM is unaccessible through the network. Right now although we have cloud-init seemingly enabled on ESX, this is due to another bug (or feature?) where cloud-init is automatically enabled when a single datasource is provided in the datasources list (In our case we set `datasource_list: [ Ec2, None ]`, which is considered as the single datasource Ec2, since None isn't counted. You can see this logic in action by looking at the contents of `/run/cloud-init/ds-identify.log` on a dcenter VM). Although none of the Ec2 meta-data is actually fetched since the VM rightfully fails to contact the Ec2 meta-data server, the network configuration is still done by cloud-init through DHCP at early boot. In the past, when we tried to enable cloud-init for other cloud platforms, we ended up breaking our ESX deployments and had to revert that change (see https://github.com/delphix/appliance-build/pull/235).

On a non-cloud deployment such as ESX, we can have cloud-init enabled by creating `meta-data` and `user-data` files in `/var/lib/cloud/seed/nocloud/`. The `meta-data` file must contain the instance-id of this particular instance in the following format:
```
$ cat /var/lib/cloud/seed/nocloud/meta-data
{instance-id: <my-custom-instance-id>}
```
When you install an Ubuntu-18-04 system manually, the installer creates those files for you.

When cloud-init detects changes in instance id, it will re-run a lot of its configuration logic, in particular logic related to network configuration. This is very useful in the cloud, when creating new instances by cloning existing ones.

In order to be more resilient to changes in interface names, cloud-init uses MAC address matching when configuring interfaces. However, this means that if the MAC address changes, then the initial cloud-init network configuration is not valid anymore, and network doesn't come up on reboot. 

This is problematic on dcenter, since we boot up the OVA once before creating the dcenter group, and so the networking will be first configured at that point. Then, when the dcenter group is cloned, a new MAC address is assigned to the VM, so networking doesn't come up for that VM anymore.

My first idea was to simply reset cloud-init before creating the dcenter group so that it re-runs again on the first boot of the cloned VM. This worked, however this didn't cover another very common use case: cloning an existing VM.

I had a few options to overcome this issue:
a) Make some changes to cloud init so that MAC address matching is not used when configuring network interfaces.
b) Add some pre-clone or post-clone logic to reset cloud-init.
c) Have cloud-init automatically detect changes in instances (i.e. implement a similar logic to how cloud does it).

Option a) wasn't ideal since we are currently leverage MAC address matching for migrating network interface configurations from Illumos to Linux. Also, MAC address matching seems like a good feature to have given that network interfaces can change names or move around in some cases.

Option b) didn't seem very practical. We'd have had to call cloud-init reset while the VM is still up, which is not always the case when taking a dcenter snapshot. post-clone this would have to rely on open-vm-tools since networking wouldn't be up anymore, and would have required a second reboot since the cloud-init reset would probably have happened after cloud-init has passed the network config stage.

I went for option c). A reliable way to detect a change in instance is to check the system's uuid. When creating a new VM, ESX will generate a random system UUID for that VM and store it in its vmx file. It looks like the system uuid is already used by some other clouds as a an instance id judging by the users of `instance_id_matches_system_uuid()`.

## Testing

Note that currently none of our deployments use the NoCloud datasource, so the main thing that we want to test is to make sure that this change doesn't break the build of cloud-init.

- git-ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1258/

- Manually configured a dcenter VM to use NoCloud. Verified that cloud-init uses the system uuid as instance id and that it doesn't re-trigger the new instance logic on reboot when the system uuid doesn't change. Attempted a `dc clone` of that VM and verified that a new instance id was detected and that network interfaces were reconfigured with the new MAC address.

### CODE REVIEW

**Comment by pzakha** [comment]
cc: @jgallag88, @prakashsurya, @grwilson

**Comment by prakashsurya** [comment]
> This is problematic on dcenter, since we boot up the OVA once before creating the dcenter group, and so the networking will be first configured at that point. Then, when the dcenter group is cloned, a new MAC address is assigned to the VM, so networking doesn't come up for that VM anymore.

We do not (should not?) boot the OVA, and then use that booted VM to create the dcenter image, for our Linux builds. If we are doing that, it's a bug (and should be fixed rather than worked around). I specifically discussed this with Basil long ago, and we both agreed we should not do this for Linux, even if we currently do this for illumos.

**Comment by pzakha** [comment]
@prakashsurya This is definitely still happening for Linux builds. Even if we were to fix this, we'd still need this change though as it fixes the case of cloning existing VMs.

**Comment by prakashsurya** [comment]
> This is definitely still happening for Linux builds.

I'll follow up with the devops team to better understand what's going on here. That's broken.

> Even if we were to fix this, we'd still need this change though as it fixes the case of cloning existing VMs.

Yes, I agree.

I presume cloning existing VMs currently works due to the bug/feature you described?

**Comment by pzakha** [comment]
> I'll follow up with the devops team to better understand what's going on here. That's broken.

Thanks. Note that we have the same issue on our Azure dcoa images. See https://jira.delphix.com/browse/DLPX-61229 as a resulting bug.

> I presume cloning existing VMs currently works due to the bug/feature you described?

That's right

**Pull request merged**
