### PR TITLE
TOOL-17954 Add environment variable to fix cloud-init build

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
@grwilson looks like this file is currently causing a merge conflict.. our difference is relatively small:
```
> g d HEAD..origin/upstreams/6.0/stage tools/read-version
diff --git a/tools/read-version b/tools/read-version
index 8302a167..9eaecb33 100755
--- a/tools/read-version
+++ b/tools/read-version
@@ -68,12 +68,7 @@ travis_ci_release_br = bool(
 )
 is_release_branch_ci = bool(github_ci_release_br or travis_ci_release_br)

-# Delphix: we set our own version
-# pylint: disable=w0125
-if True:
-    version = src_version
-    version_long = None
-elif is_gitdir(_tdir) and which("git") and not is_release_branch_ci:
+if is_gitdir(_tdir) and which("git") and not is_release_branch_ci:
     # This cmd can be simplified to ["git", "branch", "--show-current"]
     # after bionic EOL.
     branch_name = tiny_p(["git", "rev-parse", "--abbrev-ref", "HEAD"]).strip()
```

but even so, it's causing conflict.. I'm not sure how best to address this moving forward..

the problem is, we don't have the upstream tags, and even if we did, our history wouldn't align such that the `git describe` call succeeds.. we could maintain this diff, and just resolve conflicts when they arise.. or potentially "hack" one of these environment variables in the linux-pkg build logic, such that `is_release_branch_ci` gets set to true.. 
```
 60 # If we're performing CI for a new release branch (which our tooling creates
 61 # with an "upstream/" prefix), then we don't want to enforce strict version
 62 # matching because we know it will fail.
 63 github_ci_release_br = bool(
 64     os.environ.get("GITHUB_HEAD_REF", "").startswith(f"upstream/{src_version}")
 65 )
 66 travis_ci_release_br = bool(
 67     os.environ.get("TRAVIS_PULL_REQUEST_BRANCH", "").startswith("upstream/")
 68 )
 69 is_release_branch_ci = bool(github_ci_release_br or travis_ci_release_br)
 ```
 
while the "hack the environment" approach might work for now (I think it'd just be a one line change to the linux-pkg `config.sh` file, plus comments), it isn't obvious and might lead to confusion later.. but, at the same time, if we modify this script, we have to deal with merge conflicts.. so, I'm not sure which approach I like between the two..
 
 what do you think? do you have opinions on which approach seems better to you? maybe the environment hack wouldn't be too bad, as long as we add sufficient code comments to explain the situation?

**Comment by prakashsurya** [comment]
Here's what the linux-pkg change would look like: https://github.com/delphix/linux-pkg/pull/272

I'm testing this PR, in conjunction with that linux-pkg PR, [here](http://selfservice.jenkins.delphix.com/job/linux-pkg/job/6.0/job/stage/job/build-package/job/cloud-init/job/pre-push/42/)

**Comment by grwilson** [comment]
I think doing the hack might be a better approach. I guess the one issue would be if for some reason they change the logic in this script which causes our version to pick up the wrong thing. Would we detect that easily?

**Comment by prakashsurya** [comment]
> Would we detect that easily?

If it's changed in a way that fails the package build, then yes, we'll detect it via the `ab-pre-push` testing we do on upstream syncs.

I'll move forward with this approach.

**Review by grwilson — APPROVED** [review]

**Review by pcd1193182 — APPROVED** [review]

**Pull request merged**
