### PR TITLE
Merge failure

### PR DESCRIPTION
**Pull request by pcd1193182**
This PR fixes a merge failure with upstream as seen in http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/update-package/job/cloud-init/4/console. The merge issue happened in DataSourceAzure.py, with the matching logic, and in ssh_util.py where upstream attempted to change the logic in `extract_authorized_keys`; they changed it to append the default file to the auth_key_fns list, while we have it set as the only entry in the list. I preserved the delphix functionality in both cases.

http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4606/

### CODE REVIEW

**Review by pzakha — COMMENTED** [review]
Looks like the cloud-init unit test `TestMultipleSshAuthorizedKeysFile.test_multiple_authorizedkeys_file_order2 __` is failing. If that doesn't apply to the Delphix use case we may consider removing it.

**Comment by pzakha** [comment]
@pcd1193182 I see you've pushed some new code to the PR's branch. Are you still in the process of testing or do you have new changes that are ready to be reviewed?

**Comment by pcd1193182** [comment]
Test was removed since it doesn't apply to our use case. http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4655/

**Review by pzakha — APPROVED** [review]
Pending test results

**Review by prakashsurya — APPROVED** [review]

**Pull request merged**
