### PR TITLE
DLPX-64359 GCP fails to query instance metadata

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1704/)

**Comment by prakashsurya** [comment]
As far as I can tell, none of the current service dependencies for "cloud-init" ensure it waits for DNS before it starts. Since "cloud-init" relies on DNS, we need to add the service dependency on "systemd-resolved" to ensure DNS is up, by the time "cloud-init" runs.

I manually made this change on a VM running in GCP, then rebooted the system, and verified (by inspecting `/var/log/cloud-init.log`) the address resolution worked on the next boot.

**Comment by prakashsurya** [comment]
cc: @pzakha

**Comment by prakashsurya** [comment]
@sebroy Yea, I think I agree. Since we pull from Ubuntu, we likely still need this in our fork, since we'd push to upstream and then have to wait for that to reach ubuntu's (source) package to get the fix.

I'll look into how to contribute this upstream, though.

**Comment by pzakha** [comment]
We should grep for `Found ordering cycle on` in `journalctl` just to make sure we are not running into some weird dependency loop issues. Might also be a good idea to test migration since we are inserting extra dependencies on networking there.

It would be interesting to look online to see if others have run into this. It's quite suspicious that such a basic error case was not found by the cloud-init team (or at least whoever implemented GCP support for it).

**Comment by pzakha** [comment]
> I'll look into how to contribute this upstream, though.

I can help you with that, I've got a pending upstream commit with cloud-init.
We may also get some useful feedback from their team as to why this dependency was not included already. I have a feeling that there is some reasoning behind that, as well as to why AWS use an IP for querying the metadata instead of a domain name.

**Comment by prakashsurya** [comment]
> We should grep for Found ordering cycle on in journalctl just to make sure we are not running into some weird dependency loop issues.
```
$ sudo journalctl | grep "Found ordering cycle on" | wc -l
0
```

> Might also be a good idea to test migration since we are inserting extra dependencies on networking there.

`git-ab-pre-push --test-upgrade-from 5.3.5.0` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1705/)

**Comment by prakashsurya** [comment]
From all my testing, I think this is good to go.

With that said, @pzakha suggested that we instead push this change upstream, and wait to land until it's landed upstream. Thus, I've opened a merge request with upstream, [here](https://code.launchpad.net/~pkashsurya/cloud-init/+git/cloud-init/+merge/370335) (at least, I think I did, I'm new to launchpad so I may have botched something).

**Comment by sebroy** [comment]
IMO we have a fix that's tested that that works, let's merge this when it's ready. We'll pull in and merge the upstream fix eventually when that gets done.

**Comment by grwilson** [comment]
I agree with @sebroy that we should just merge this change while you continue to work with the cloud-init developers to get this fixed upstream.

**Comment by pzakha** [comment]
Yeah I agree. Just to clarify, I wasn't insisting on waiting for this to land upstream. I just wanted to get some feedback from the maintainers, and it seems like we got some. I will merge this whenever you feel like this is ready @prakashsurya .

**Comment by prakashsurya** [comment]
@pzakha I think it's good to go, now that it's passed upgrade testing with the latest version.

**Pull request merged**
