### PR TITLE
DLPX-81845 cloud-init sync with upstream is failing

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/2348/)

**Comment by pcd1193182** [comment]
Can you post the list of conflicts or problems the merge was having and how they were resolved?

**Comment by prakashsurya** [comment]
Oh yea.. Can you remind me how we've done that in the past? Do we have that documented anywhere?

Is the process to first commit with the conflicts, then fix in a separate commit, and show the diff for that commit?

I forget how I did that in the past. I'll have to redo the merge, but not a big deal.

**Comment by pcd1193182** [comment]
I think in the past we usually just post a list in the comments of the files that had merge conflicts and how they were resolved. If you want something more programatic, I think you can post the original conflicting blocks with the `>>>>>>>>` and `<<<<<<<<<`

**Comment by prakashsurya** [comment]
@pcd1193182 I've updated this PR to highlight the conflicts and resolutions; these can be seen [here](https://github.com/delphix/cloud-init/pull/56/commits/679df7984abb5c66e27347ab385fb9c6c1147eb0).

**Review by pcd1193182 — APPROVED** [review]

**Review by grwilson — APPROVED** [review]

**Pull request merged**
